export type ProductFact = Record<string, string>;

export type ImageGenerationModel = "smart-elderly" | "gpt2" | "nano-banana" | "seedream5";

export type ReferenceMaterial = {
  name: string;
  type: string;
  size: number;
  /** A provider-ready image input. Archive files intentionally have no source. */
  source?: {
    kind: "data_url" | "url" | "file_id" | "file_path" | "asset_id";
    value: string;
  };
};

export type OrchestratorInput = {
  productFacts: ProductFact[];
  referenceMaterials: ReferenceMaterial[];
  generationRequirements: string;
  imageModel: ImageGenerationModel;
  workflowCapabilities?: WorkflowCapabilityDescriptor[];
};

export type WorkflowCapabilityDescriptor = {
  id: string;
  name: string;
  description: string;
  imageInputs: Array<{
    key: string;
    description: string;
  }>;
  textInputs?: Array<{
    key: string;
    description: string;
    generatedByOrchestrator: boolean;
  }>;
};

export type OrchestratorTask = {
  taskId: string;
  imageType: string;
  imageLabel: string;
  instruction: string;
  references?: string[];
  /** Required for models that dispatch through a fixed workflow capability. */
  capabilityId?: string;
  /** Logical workflow image input key -> exact reference material name. */
  inputBindings?: Record<string, string>;
  /** Logical workflow text input key -> task-specific text generated by the orchestrator. */
  parameters?: Record<string, string>;
};

export type OrchestratorPlan = {
  summary: string;
  categories: Array<{
    categoryKey: string;
    categoryLabel: string;
    tasks: OrchestratorTask[];
  }>;
  clarificationQuestions?: string[];
  unsupportedRequirements?: string[];
};

export type TaskStatus =
  | "planned"
  | "generating"
  | "completed"
  | "failed";

export type GenerationAttempt = {
  id: string;
  prompt: string;
  referenceMaterials: ReferenceMaterial[];
  inputBindings?: Record<string, string>;
  status: TaskStatus;
  imageUrl?: string;
  errorMessage?: string;
  cost?: number;
  createdAt: string;
  completedAt?: string;
};

export type GenerationTask = OrchestratorTask & {
  categoryKey: string;
  categoryLabel: string;
  status: TaskStatus;
  imageUrl?: string;
  errorMessage?: string;
  cost?: number;
  effectivePrompt?: string;
  attempts?: GenerationAttempt[];
};

export type ImageGenerationInput = {
  productFacts: ProductFact[];
  referenceMaterials: ReferenceMaterial[];
  generationRequirements: string;
  task: GenerationTask;
  prompt: string;
  imageModel: ImageGenerationModel;
  textInputOverrides?: Record<string, string>;
};

export type ImageGenerationResult = {
  imageUrl: string;
  cost?: number;
};

export type MaterialWorkflowStatus = "idle" | "planning" | "running" | "completed" | "failed";

export type MaterialGenerationSource = "web" | "mcp";

export type MaterialGenerationJobStatus = "queued" | "planning" | "running" | "completed" | "failed";

export type MaterialGenerationJob = {
  id: string;
  workflowId: string;
  nodeId: string;
  spuId: string;
  source: MaterialGenerationSource;
  idempotencyKey?: string;
  status: MaterialGenerationJobStatus;
  imageModel: ImageGenerationModel;
  generationRequirements: string;
  productFacts: ProductFact[];
  referenceMaterials: ReferenceMaterial[];
  plan: OrchestratorPlan | null;
  tasks: GenerationTask[];
  errorMessage?: string;
  previewImageUrl?: string;
  createdAt: string;
  startedAt?: string;
  updatedAt: string;
  completedAt?: string;
};

export type MaterialGenerationJobSummary = Omit<
  MaterialGenerationJob,
  "productFacts" | "referenceMaterials" | "generationRequirements" | "plan" | "tasks"
> & {
  totalCount: number;
  completedCount: number;
  failedCount: number;
};

export type CreateMaterialGenerationJobInput = OrchestratorInput & {
  workflowId: string;
  nodeId: string;
  spuId: string;
  source: MaterialGenerationSource;
  imageModel: ImageGenerationModel;
  idempotencyKey?: string;
};

export type RetryMaterialGenerationTaskInput = {
  prompt: string;
  referenceMaterials: ReferenceMaterial[];
  inputBindings?: Record<string, string>;
};
